#!/usr/bin/env bash
#
# A simle program to pretty-print variable contents for debugging purposes.
#
# Autor: Edvin Lidholm
# License: MIT
# Date: 2025-12-05
#

vardump() {
  local color=true
  local verbose=false
  local OPTIND opt
  while getopts 'cvh' opt; do
    case "$opt" in
      c) color=false ;;
      v) verbose=true ;;
      h)
        echo "Usage: vardump [-c] [-v] <var_name>"
        echo
        echo "Options:"
        echo "  -c    Disable colored output"
        echo "  -v    Enable verbose output"
        echo "  -h    Show this help message"
        return 0
        ;;
      *)
        echo "Error: unknown option '$opt'" >&2
        return 1
        ;;
    esac
  done
  shift "$((OPTIND -1))"

  var_name=$1
  if [[ -z "$var_name" ]]; then
    echo "Error: missing required argument '<var_name>'" >&2
    return 1
  fi

  if ! declare -p "$var_name" &>/dev/null; then
    echo "variable '$var_name' is not defined" >&2
    return 1
  fi

}

vardump "$@"
